name: NodeJS CD

on:
  pull request:
    branches: 
      - master
      - main


jobs:
  cd:
    name: "Terraform CD"
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Terraform"
        uses: hashicorp/etup-terraform@v1
      
      - name: "Initialise Terraform"
        run: terraform init

      - name: "Terraform Plan"
        run: terraform plan

      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test