name: NodeJS CD

on:
  pull request:
    branches: [ master, main ]


jobs:
  cd:
  - name: "Checkout"
    uses: actions/checkout@v3

  - name: "Setup Terraform"
    uses: hashicorp/etup-terraform@v1
  
  - name: "Initialise Terraform"
    run: terraform init

  - name: "Terraform Plan"
    run: terraform plan
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@1
    with:
    node-version: 12
    - run: echo "running CD pipeline"
    - run: npm run build